image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

before_script:
  - apk update && apk add ca-certificates
  - echo $INTERNAL_CA_ROOT > /usr/local/share/ca-certificates/internal_ca_root.crt
  - update-ca-certificates
  - echo $CI_REGISTRY
  - echo $CI_REGISTRY_IMAGE
  - echo $CI_REGISTRY_USER
  - echo $IMAGE_NAME
  - echo $TAG_NAME
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - master
    - develop
    - tags

release:
  stage: release
  script:
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $TAG_NAME
    - docker push $TAG_NAME
  only:
    - tags
