image: docker:latest

services:
  - name: docker:dind
    command:
      - /bin/sh
      - -c
      - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/ca.crt && update-ca-certificates && dockerd-entrypoint.sh || exit

stages:
- build
- test
- release

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  REF_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  TAG_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

before_script:
  - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/ca.crt
  - update-ca-certificates --fresh > /dev/null

  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  interruptible: true
  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker tag $IMAGE_NAME $REF_NAME
    - docker push $REF_NAME
  only:
    - master
    - develop
    - tags

release:
  stage: release
  script:
    - docker pull $IMAGE_NAME
    - docker tag $IMAGE_NAME $TAG_NAME
    - docker push $TAG_NAME
  only:
    - tags
