image: docker:latest

services:
  - name: docker:dind

stages:
  - build
  - deploy  # dummy stage to follow the template guidelines
  - review
  - dast
  - staging
  - canary
  - production
  - incremental rollout 10%
  - incremental rollout 25%
  - incremental rollout 50%
  - incremental rollout 100%
  - cleanup

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA
  REF_NAME: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:latest
  CI_APPLICATION_REPOSITORY: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME
  CI_APPLICATION_TAG: $CI_COMMIT_SHA

.docker_preset: &docker_preset
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  <<: *docker_preset
  stage: build
  interruptible: true
  script:
    - docker build --pull -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
    - docker tag $IMAGE_NAME $REF_NAME
    - docker push $REF_NAME
  only:
    - master
    - develop
    - tags

include:
  - template: Jobs/Deploy.latest.gitlab-ci.yml
