# Generated by Django 3.1.1 on 2020-11-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scope',
            index=models.Index(fields=['service', 'resource', 'action', 'selector'], name='pegasus_sco_service_b0b5d3_idx'),
        ),
    ]
