# Generated by Django 3.1.1 on 2020-11-11 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default_role',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(default_role=True), fields=('default_role',), name='default_role_unique'),
        ),
    ]
