# Generated by Django 3.1.1 on 2020-11-13 13:02

from django.db import migrations, models
import django.db.models.deletion
import pegasus.models.tenant


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0002_auto_20201112_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantCountry',
            fields=[
                ('id', models.CharField(default=pegasus.models.tenant._default_tenant_id, editable=False, max_length=16, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='ISO 3166 Alpha-2 Country Code', max_length=2)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='pegasus.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tenantcountry',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='tenant_code_unique'),
        ),
    ]
