# Generated by Django 3.1.1 on 2020-11-09 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0002_auto_20201109_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesstoken',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
