# Generated by Django 3.1.1 on 2020-11-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0005_remove_role_included_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='included_roles',
            field=models.ManyToManyField(blank=True, related_name='_role_included_roles_+', to='pegasus.Role'),
        ),
    ]
