# Generated by Django 3.2.5 on 2021-09-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0017_userotp_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='tenant_email_unique',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'TERMINATED'), _negated=True), fields=('tenant', 'email'), name='tenant_email_unique'),
        ),
    ]
