# Generated by Django 3.2.5 on 2021-09-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0018_auto_20210917_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
