# Generated by Django 3.2.5 on 2021-10-06 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pegasus.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('pegasus', '0019_user_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlag',
            fields=[
                ('id', models.CharField(default=pegasus.models.user._default_user_flag_id, max_length=72, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userflag',
            constraint=models.UniqueConstraint(fields=('user', 'key'), name='user_flag_key_unique'),
        ),
    ]
