# Generated by Django 3.1.1 on 2020-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0004_auto_20201116_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('service', 'Service')], default='user', max_length=16),
        ),
        migrations.AlterField(
            model_name='role',
            name='scopes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'is_internal': False}, related_name='roles', to='bb_access.Scope'),
        ),
        migrations.AlterField(
            model_name='useraccesstoken',
            name='scopes',
            field=models.ManyToManyField(limit_choices_to={'is_active': True, 'is_internal': False}, related_name='user_access_tokens', to='bb_access.Scope'),
        ),
    ]
