# Generated by Django 3.1.1 on 2020-11-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0007_role_is_active'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(is_default=True), fields=('is_default',), name='is_default_unique'),
        ),
    ]
