# Generated by Django 3.1.1 on 2020-12-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0008_auto_20201130_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('USER', 'User'), ('SERVICE', 'Service')], default='USER', max_length=16),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='type',
            field=models.CharField(choices=[('USER', 'User Token')], max_length=16),
        ),
    ]
