# Generated by Django 3.1.1 on 2021-02-22 09:05

from django.db import migrations, models
import django.db.models.deletion


def set_tenant_on_users(apps, schema_editor):
    User = apps.get_model('bb_access', 'User')
    Tenant = apps.get_model('bb_access', 'Tenant')

    tenant = Tenant.objects.first()

    users = User.objects.filter(tenant__isnull=True)
    for user in users:
        user.tenant = tenant
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0013_auto_20210222_1003'),
    ]

    operations = [
        migrations.RunPython(set_tenant_on_users),
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='users', to='bb_access.tenant'),
        ),
    ]
