# Generated by Django 3.1.1 on 2021-03-10 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import bb_access.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0015_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccesstoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usertoken',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.CharField(default=bb_access.models.user._default_user_otp_id, max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PIN', 'PIN'), ('TOKEN', 'Token')], db_index=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('value', models.CharField(max_length=128)),
                ('is_internal', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='userotp',
            constraint=models.UniqueConstraint(fields=('user', 'type', 'used_at'), name='user_type_used_at_unique'),
        ),
    ]
