# Generated by Django 3.1.1 on 2021-03-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0016_auto_20210310_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='length',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
    ]
