# Generated by Django 3.2.5 on 2021-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0020_auto_20211006_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=320),
        ),
    ]
