# Generated by Django 4.0.5 on 2022-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0022_remove_scope_bb_access_sco_service_f0db87_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_kafka_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
