# Generated by Django 4.0.7 on 2022-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bb_access', '0027_user_gender_userotp_last_kafka_publish_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
